services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: autotransform
      POSTGRES_DB: autotransform
      POSTGRES_PASSWORD: autotransform
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autotransform"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: autotransform-prod:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment:
      ENVIRONMENT: prod
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PROCESSING_DEBUG: true
      POSTGRES_URI: postgresql+asyncpg://autotransform:autotransform@postgres:5432/autotransform
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app-data:/app-data
    restart: always