services:
  - type: web
    name: autotransform
    plan: free
    runtime: docker
    repo: https://github.com/pateli18/autotransform
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    buildFilter:
      ignoredPaths:
        - .vscode/**
        - docker-compose*
    envVars:
      - key: BASE_URL
        fromService:
          name: autotransform
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: POSTGRES_URI
        fromDatabase:
          name: autotransformdb
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 1
      - key: ENVIRONMENT
        value: prod
      - key: PROCESSING_DEBUG
        value: false
      - key: GIT_PROVIDER
        value: github
      - key: GIT_PROVIDER_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FILE_PROVIDER
        value: local
      - key: FILE_PROVIDER_CONFIG
        value: '{"save_path": "/app-data/"}'
      - key: LOG_LEVEL
        value: INFO
databases:
  - name: autotransformdb
    postgresMajorVersion: "15"
    plan: free
